2025-01-02 15:11:42,679 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Zver\PycharmProjects\Chat_Bot_Telegramm\test_12_4.py", line 20, in test_run
    runner2 = Runner(2)
  File "C:\Users\Zver\PycharmProjects\Chat_Bot_Telegramm\module_12_log.py", line 7, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-02 15:11:42,682 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Zver\PycharmProjects\Chat_Bot_Telegramm\test_12_4.py", line 11, in test_walk
    runner1 = Runner('Nik', -5)
  File "C:\Users\Zver\PycharmProjects\Chat_Bot_Telegramm\module_12_log.py", line 12, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
